### ISSUE TITLE
monthly build fails

### ISSUE THREAD

**Issue by cwmeijer** [NLeSC/mcfly#165]
Some of the builds are failing. When trying 3.6 in a docker.
I get the following behavior:

>>> 
>>> 
>>> 
>>> 
>>> from mcfly import find_architecture
Using TensorFlow backend.
/opt/conda/envs/test-environment/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: compiletime version 3.5 of module 'tensorflow.python.framework.fast_tensor_util' does not match runtime version 3.6
  return f(*args, **kwds)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/mcfly/mcfly/find_architecture.py", line 15, in <module>
    from sklearn import neighbors, metrics as sklearnmetrics
  File "/opt/conda/envs/test-environment/lib/python3.6/site-packages/sklearn/__init__.py", line 134, in <module>
    from .base import clone
  File "/opt/conda/envs/test-environment/lib/python3.6/site-packages/sklearn/base.py", line 11, in <module>
    from scipy import sparse
  File "/opt/conda/envs/test-environment/lib/python3.6/site-packages/scipy/sparse/__init__.py", line 229, in <module>
    from .csr import *
  File "/opt/conda/envs/test-environment/lib/python3.6/site-packages/scipy/sparse/csr.py", line 15, in <module>
    from ._sparsetools import csr_tocsc, csr_tobsr, csr_count_blocks, \
ImportError: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `CXXABI_1.3.9' not found (required by /opt/conda/envs/test-environment/lib/python3.6/site-packages/scipy/sparse/_sparsetools.cpython-36m-x86_64-linux-gnu.so)
>>> from mcfly import find_architecture
KeyboardInterrupt
>>> 
(test-environment) root@e2cff93680a6:/mcfly# python
Python 3.6.3 |Anaconda, Inc.| (default, Nov  9 2017, 00:19:18) 
[GCC 7.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from scipy import sparse
>>> from mcfly import find_architecture
Using TensorFlow backend.
/opt/conda/envs/test-environment/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: compiletime version 3.5 of module 'tensorflow.python.framework.fast_tensor_util' does not match runtime version 3.6
  return f(*args, **kwds)
>>> from mcfly import find_architecture
>>> from mcfly import find_architecture
>>> 

It could be that conda is using some version of this libstdc++.so.6 than scipy comes with. Important detail is that Scipy did a 1.0.0 release 22 days ago so this almost has to have something to do with it.
https://github.com/scipy/scipy/releases

**Comment by cwmeijer** [comment]
This was fixed last year.
